version: '3'

services:
  api_upload:
    build:
      context: ./express-file-upload
      dockerfile: Dockerfile
    container_name: api_upload_file2
    restart: unless-stopped
    volumes:
      - ./express-file-upload:/usr/src/app
      - express-file-upload:/usr/src/app/node_modules
    ports:
      - 8080:8080

volumes:
 express-file-upload:

